### PR TITLE
Implement last picker phase getter

### PR DESCRIPTION
**Pull request by tbydza**
The picker has 3 distinct phases: picking date, picking hours an picking minutes.
So I implemented getter to get last phase.
Phases are: `"date"`, `"hour"` and `"minute"`.
Instance of SveltyPicker now has function `getLastPickerPhase()`, which will return last phase.

```svelte
<script>
  let picker;
  function onChange(e) {
    const phase = picker.getLastPickerPhase();
    if (phase === "minute") doSomething(e.detail)
  }
</script>
<SveltyPicker bind:this={picker} on:change={onChange} />
```

### CODE REVIEW

**Comment by tbydza** [comment]
PR for  this feature request: #94

**Comment by mskocik** [comment]
I can imagine sending this on `change` event, but that would be huge BC break. Maybe I will add it in v4.

Btw, can you add mention of in into README as well?

**Comment by tbydza** [comment]
> I can imagine sending this on `change` event, but that would be huge BC break. Maybe I will add it in v4.
> 
> Btw, can you add mention of in into README as well?

No problem, I will update README as well. Otherwise, is the code ok?

**Comment by tbydza** [comment]
I updated only main `REAME.md`, should I also update `routes/_README.md` or `options.md`?
Btw, shouldn't the `docs` folder be in .gitignore, when it is generated from other files?

**Comment by mskocik** [comment]
Code is okay, `docs` folder is being used by github pages. No need to updates routes/readme, because the whole web needs re-write :)
Who will need this feature, will find it on github.

**Pull request merged**
