### PR TITLE
CSS vars & DOCS theme improvements

### PR DESCRIPTION
**Pull request by Mero-Plaform**

### CODE REVIEW

**Comment by mskocik** [comment]
I had to push new commit into the `main` branch to set end of lines to `LF` because your PR marked whole files as changes, which I couldn't merge. Please rebase you branch on latest `main`.

**Comment by Mero-Plaform** [comment]
Now, I guess, things become better. 

Sorry for that.

**Comment by mskocik** [comment]
No need for update related to `tokens.css` I didn't convert the EOLs because that file is related to docs only.

Thanks for the PR. Will release new version soon, probably tomorrow. There are some bits I would like to add as well for the next major release.

**Comment by mskocik** [comment]
Unfortunarely I have to delay the release. I am leaving for whole week, so I didn't have time for it today. Hopefully it won't be a bit problem for, in the meantime you can install directly from main branch

**Comment by Mero-Plaform** [comment]
Yeah, it won't make a problem at all. 

Thx for letting me know, have a good time.

**Pull request merged**
