### PR TITLE
Add close and time-close event

### PR DESCRIPTION
**Pull request by sadegh19b**

### CODE REVIEW

**Review by mskocik — CHANGES_REQUESTED** [review]
It's obvious from the first glance, that this event won't be triggered when you have picker in 'date' mode only. 
Also I wouldn't say this is the best place to put it.

Test it in all use cases, before you consider this final.

**Comment by sadegh19b** [comment]
Hi @mskocik ,  yes you right, i fixed that problem, now i think it's ok.

**Review by mskocik — CHANGES_REQUESTED** [review]
Again, this is incomplete. Event is not triggered in _every_ possible case, when picker is closed and when in date mode close event is trigged twice.

**Comment by sadegh19b** [comment]
Hi again @mskocik , please check it again.
thank you

**Comment by mskocik** [comment]
It's getting messy and I don't like it. It's not very well thought.

It could be done in simpler fashion. It would be enough to have just one "close". If you want to differenciate between 'time' and 'date' close event, just send the "type" in the event detail.

And btw you are still missing one case when event is not fired, it's keyboard related, but it should be there for completeness

**Comment by sadegh19b** [comment]
@mskocik , If possible, do the necessary modifications yourself.
thank you.

**Comment by mskocik** [comment]
I have no free time for it. And because it is really specific feature, it has very low priority for me. You can still use your own fork.

**Pull request closed without merging**
